---
title: "LCGA and GMM"
author: "Bruce Zhou"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lcmm)
library(haven)
```

## Data Wrangling

```{r data wrangling}
rm(list=ls())
setwd('/Users/bruce/Desktop/Prof. Wang lab/hearing-clustering')

df <- read_csv('data/nhanes_1520_age.csv')
left_var_list <- c('SEQN', 'AUXU500L', 'AUXU1K1L', 'AUXU2KL', 'AUXU3KL', 'AUXU4KL', 'AUXU6KL', 'AUXU8KL')
right_var_list <- c('SEQN', 'AUXU500R', 'AUXU1K1R', 'AUXU2KR', 'AUXU3KR', 'AUXU4KR', 'AUXU6KR', 'AUXU8KR')

df_left <- df %>%
  select(all_of(left_var_list))
colnames(df_left) <- c('SEQN', '500 Hz', '1 kHz', '2 kHz', '3 kHz', '4 kHz', '6 kHz', '8 kHz')
df_right <- df %>%
  select(all_of(right_var_list))
colnames(df_right) <- c('SEQN', '500 Hz', '1 kHz', '2 kHz', '3 kHz', '4 kHz', '6 kHz', '8 kHz')

df_left$SEQN <- seq_along(df_left$SEQN)
df_right$SEQN <- seq_along(df_right$SEQN) + 9729

df <- bind_rows(df_left, df_right)

df <- df %>%
  pivot_longer(cols = colnames(df_left)[-1], names_to = "frequency", values_to = "threshold") %>%
  filter(threshold != 888 & threshold != 666 & !is.na(threshold))

df <- df %>%
  arrange(SEQN) %>%
  group_by(SEQN) %>%
  mutate(frequency = row_number()) %>%
  ungroup()
```

## LCGA

```{r LCGA analysis}
# open package library(lcmm)
# set the seed for random number generator, so results can be # reproduced:
set.seed(2002)

# run models with 1-4 classes, each with 100 random starts
# using the 1-class model to set initial start values:

lcga1 <- hlme(threshold ~ frequency, subject = "SEQN", ng = 1, data = df)

lcga2 <- gridsearch(rep = 100, maxiter = 10, minit = lcga1, m=hlme(threshold ~ frequency + I(frequency^2), subject = "SEQN", ng = 2, data = df, mixture = ~ frequency))

lcga3 <- gridsearch(rep = 100, maxiter = 10, minit = lcga1, m=hlme(threshold ~ frequency, subject = "SEQN", ng = 3, data = df, mixture = ~ frequency))

lcga4 <- gridsearch(rep = 100, maxiter = 10, minit = lcga1, m=hlme(threshold ~ frequency, subject = "SEQN", ng = 4, data = df, mixture = ~ frequency))

# make table with results for the 3 models: summarytable(lcga1, lcga2, lcga3)
summarytable(lcga1, lcga2, lcga3, lcga4)
```




